---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/DavidAnson/markdownlint-cli2.git
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/koalaman/shellcheck-precommit.git
    rev: v0.11.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write
        language: node
        types:
          - markdown
        additional_dependencies:
          - prettier@3.6.2
